[workspace]
authors = ["cad3n123 <cadencrowson@gmail.com>"]
channels = ["conda-forge"]
name = "image_processor"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pyqt6 = ">=6.8.1,<7"
pillow = ">=10.0.0,<11"
numpy = ">=1.26.0,<2"
rembg = "*"
pymupdf = "*"