[workspace]
authors = ["cad3n123 <cadencrowson@gmail.com>"]
channels = ["conda-forge"]
name = "image_processor"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
start = { cmd = "python main.py", env = { QT_PLUGIN_PATH = "lib/qt6/plugins" } }

[activation]
# This ensures the variable is set whenever the environment is active
scripts = ["export QT_PLUGIN_PATH=$CONDA_PREFIX/lib/qt6/plugins"]

[dependencies]
python = "3.11.*"
pyqt6 = ">=6.8.1,<7"
pillow = ">=10.0.0,<11"
numpy = ">=1.26.0,<2"
rembg = "*"

[pypi-dependencies]
pymupdf = "*"
